"""My initial Migration

Revision ID: 758ad7b1398a
Revises: 
Create Date: 2022-09-16 15:58:31.077206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758ad7b1398a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
